version: 0.2

env:
  variables:
    REGION: "eu-west-1"
    CLUSTER_NAME: "cinema-cluster"
    ACCOUNT_ID: "634733903398"
    CODEBUILD: "true"
    DEBIAN_FRONTEND: "noninteractive"
    AWS_DEFAULT_REGION: "eu-west-1"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update -y
      - apt-get install -y jq awscli
      - echo "Dependencies installed"
  
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo "Logged into ECR"
      - echo "Setting up environment for deployment..."
      - export AWS_DEFAULT_REGION=$REGION
      - echo "Environment configured for region: $REGION"
  
  build:
    commands:
      - echo "Running deployment script..."
      - chmod +x deploy-cinema-aws.sh
      - bash deploy-cinema-aws.sh
      - echo "Deployment completed successfully!"
  
  post_build:
    commands:
      - echo "Build & Deploy finished!"
      - echo "Checking deployment status..."
      - |
        if [ -f "aws-resources.json" ]; then
          echo "Deployment resources:"
          cat aws-resources.json
        fi
      - echo "CI/CD pipeline completed successfully!"

artifacts:
  files:
    - "aws-resources.json"
    - "deploy-cinema-aws.sh"
    - "README.md"
    - "buildspec.yml"
  discard-paths: no

cache:
  paths:
    - '/root/.docker/**/*'